<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Lenovo-PC" name="com.moasis.nextgenagencyapp.tests.acceptance.LoginTests" tests="9" failures="1" timestamp="25 Sep 2015 21:35:50 GMT" time="152.976" errors="0">
  <testcase name="allElementsArePresentOnPage" time="77.281" classname="com.moasis.nextgenagencyapp.tests.acceptance.LoginTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.moasis.nextgenagencyapp.pages.LoginPage.assertAllElementsArePresent(LoginPage.java:87)
	at com.moasis.nextgenagencyapp.tests.acceptance.LoginTests.allElementsArePresentOnPage(LoginTests.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- allElementsArePresentOnPage -->
  <testcase name="dashboardLoadsAfterLogin" time="8.469" classname="com.moasis.nextgenagencyapp.tests.acceptance.LoginTests"/>
  <testcase name="noUsernameEnteredSaysRequired" time="9.542" classname="com.moasis.nextgenagencyapp.tests.acceptance.LoginTests"/>
  <testcase name="badUserAndPassLoginFails" time="12.376" classname="com.moasis.nextgenagencyapp.tests.acceptance.LoginTests"/>
  <testcase name="loginPageLoads" time="4.978" classname="com.moasis.nextgenagencyapp.tests.acceptance.LoginTests"/>
  <testcase name="logoutReturnsToLogin" time="8.762" classname="com.moasis.nextgenagencyapp.tests.acceptance.LoginTests"/>
  <testcase name="badPassLoginFails" time="12.884" classname="com.moasis.nextgenagencyapp.tests.acceptance.LoginTests"/>
  <testcase name="noPasswordEnteredSaysRequired" time="6.358" classname="com.moasis.nextgenagencyapp.tests.acceptance.LoginTests"/>
  <testcase name="badUserLoginFails" time="12.326" classname="com.moasis.nextgenagencyapp.tests.acceptance.LoginTests"/>
</testsuite> <!-- com.moasis.nextgenagencyapp.tests.acceptance.LoginTests -->
